FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY Source/MQTT.DataGenerator/*.csproj ./MQTT.DataGenerator/
RUN dotnet restore ./MQTT.DataGenerator/MQTT.DataGenerator.csproj

COPY Source ./Source
RUN dotnet publish ./Source/MQTT.DataGenerator/MQTT.DataGenerator.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "MQTT.DataGenerator.dll"]
