FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY Source/MQTT.Subscriber/*.csproj ./MQTT.Subscriber/
RUN dotnet restore ./MQTT.Subscriber/MQTT.Subscriber.csproj

COPY Source ./Source
RUN dotnet publish ./Source/MQTT.Subscriber/MQTT.Subscriber.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "MQTT.Subscriber.dll"]
